- name: Stop Spark and HDFS
  hosts: master
  user: ubuntu
  vars_files:
    - ../vars/main.yml
  tasks:
    - name: stop hdfs
      script: stop_hdfs.sh
      environment:
        JAVA_HOME: "{{ java_home }}"
        HADOOP_HOME: "{{ hadoop_home }}"
        SPARK_HOME: "{{ spark_home }}"
    - name: stop Spark
      script: stop_spark.sh
      environment:
        JAVA_HOME: "{{ java_home }}"
        HADOOP_HOME: "{{ hadoop_home }}"
        SPARK_HOME: "{{ spark_home }}"
